#! /usr/bin/env python
import re, sys
from getopt import gnu_getopt, GetoptError
from subprocess import Popen, PIPE

error_re = re.compile(r'.*\bFile could not be opened\b')
inform_re = re.compile('|'.join([
  r'\s+[a-zA-Z0-9_]+\s\[\d+\]\s+Initializing\s*$',
]))
ignore_re = re.compile('|'.join([
  r'\s+$',
  r'\s+\[1\]\[eagleredtrans.gif\]$',
  r'\s+Birds Home$',
  r'\s+\[eagle-grey\.gif\]$',
  r'Pool Property Tables$',
  r'Pool Views$',
  r'\s+\[2\]PoolManager$',
  r'Pool groups of PoolManager$',
  r'\s+PoolGroup\s+Total Space/MB',
  r'\s+\[\d+\][a-zA-Z0-9_]+\s+\d+\s+\d+\s+\d+$',
  r'Pool group [a-zA-Z0-9_]+$',
  r'\s+\[\d+\]Cell View \[\d+\]Space Usage',
  r'\s+CellName\s+DomainName\s+Total Space/MB',
  r'\s+[a-zA-Z0-9_]+\s+[-a-zA-Z0-9_]+\s+\d+\s+\d+\s+\d+$',
  r'\s+_+$',
  r'\s+diskCacheV\d+\.services\.web\.PoolInfoObserverEngine',
  r'References$',
  r'\s+\d+\. http://',
]))

def check_url(url):
    cmd = ['lynx', '-width=512', '-dump', url]
    fh = Popen(cmd, shell = False, stdout = PIPE).stdout
    msgs = []
    line_count = 0
    error_count = 0
    unknown_count = 0
    for ln in fh:
	line_count += 1
	if re.match(error_re, ln):
	    error_count += 1
	    msgs.append('E ' + ln)
	elif re.match(inform_re, ln):
	    msgs.append('I ' + ln)
	elif not re.match(ignore_re, ln):
	    unknown_count += 1
	    msgs.append('U ' + ln)
    fh.close()
    if error_count:
	print 'Found %d errors.' % error_count
	status_code = 2
    elif unknown_count:
	print 'Some lines were not recognised, please update the probe.'
	status_code = 3
    elif line_count < 20:
	print 'The output is suspiciously short.'
	print '%s gives only %d lines of output.'%(' '.join(cmd), line_count)
	map(sys.stdout.write, msgs)
	status_code = 3
    else:
	print 'Scanned %d lines'%line_count
	status_code = 0
    map(sys.stdout.write, msgs)
    sys.exit(status_code)

base_url = None
page_path = None
try:
    opts, args = gnu_getopt(sys.argv[1:], 'H:g:')
    for opt, arg in opts:
	if opt == '-H':
	    base_url = 'http://%s:2288'%arg
	elif opt == '-g':
	    page_path = '/pools/list/PoolManager/%s/spaces'%arg
	else:
	    assert False
    if base_url is None:
	raise GetoptError('The -H option is mandatory.')
    if page_path is None:
	raise GetoptError('The -g option is mandatory.')
except GetoptError, xc:
    sys.stderr.write('%s\n'%xc)
    sys.exit(3)
check_url(base_url + page_path)
